Repository apache/rocketmq-client-cpp, pull requests merged in 2019-01, with the labels that each got.

#46 add ci(travis)
  .travis.yml
  build.sh
Labels: enhancement

#50 Fix push consumer dtor segfault
  src/consumer/DefaultMQPushConsumer.cpp
Labels: enhancement

#48 [Issue#44] Resolve RetrySendTimes doesn't Work for Async Send
  include/DefaultMQProducer.h
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/common/AsyncCallbackWrap.cpp
  src/common/AsyncCallbackWrap.h
  src/producer/DefaultMQProducer.cpp
  src/protocol/RemotingCommand.cpp
  src/protocol/RemotingCommand.h
  src/transport/ResponseFuture.cpp
  src/transport/ResponseFuture.h
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
Labels: enhancement

#53 [ISSUE #45]Fix unsafe code ,build warnings and format code style
  CMakeLists.txt
  include/DefaultMQProducer.h
  src/common/sync_http_client.h
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/consumer/PullRequest.h
  src/producer/DefaultMQProducer.cpp
  src/thread/disruptor/sequence.h
  src/transport/TcpTransport.cpp
Labels: bug, enhancement

#55 Properly construct DefaultMQPushConsumer
  build.sh
  src/consumer/DefaultMQPushConsumer.cpp
Labels: enhancement

#64 Enable license and travis label
  README.md
Labels: enhancement

#61 [ISSUE#43] One Consumer Consume One Message Twice at the same time
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/common/AsyncArg.h
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/consumer/PullRequest.cpp
  src/consumer/PullRequest.h
  src/consumer/Rebalance.cpp
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
Labels: bug

#59 [ISSUE #52]Fix infinite loop on tcptransport connect
  src/transport/TcpTransport.cpp
Labels: bug

#68 [ISSUE#67] Resolve CreateMessage but without DestroyMessage for example AsyncProducer and SyncProducer
  example/CAsyncProducer.c
  example/Producer.c
  example/PullConsumeMessage.c
  example/PushConsumeMessage.c
  example/common.h
  include/CCommon.h
  include/CMQException.h
  include/MQClientException.h
  src/extern/CProducer.cpp
  test/src/UrlTest.cpp
Labels: enhancement

#69 Remove the unnessesary code it may cause dead loop for some scene
  src/MQClientFactory.cpp
  src/consumer/Rebalance.cpp
Labels: enhancement

#85 [ISSUE #84] fixed duplicated opaque
  src/protocol/RemotingCommand.cpp
Labels: bug
