Repository apache/rocketmq-client-cpp, pull requests merged in 2019-04, with the labels that each got.

#105 [ISSUE #88] select slave broker when master broker is unavailable.
  src/MQClientFactory.cpp
  src/protocol/TopicRouteData.h
Labels: enhancement

#115 unit-test-common-1
  test/src/common/TopicConfigTest.cpp
  test/src/common/ValidatorsTest.cpp
  test/src/common/VirtualEnvUtilTest.cpp
Labels: unit test

#116 unit-test-common-2
  src/common/NamesrvConfig.h
  test/src/common/MemoryOutputStreamTest.cpp
  test/src/common/NamesrvConfigTest.cpp
  test/src/common/PermNametTest.cpp
  test/src/common/PullSysFlagTest.cpp
Labels: unit test

#119 [ISSUE#118] Support send message oneway orderly for C API
  include/CProducer.h
  src/extern/CProducer.cpp
Labels: enhancement

#133 [ISSUE #121]Support connect MQ endpoint with ACL
  src/MQClientFactory.cpp
  src/common/MQClient.cpp
  src/common/NameSpaceUtil.cpp
  src/common/NameSpaceUtil.h
  src/log/Logging.cpp
  src/log/Logging.h
  src/protocol/CommandHeader.cpp
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpTransport.cpp
Labels: new feature

#135 [ISSUE #134] Fixed ResponseFuture leak when invokeHeartBeat is failed.
  src/transport/TcpRemotingClient.cpp
Labels: bug
