Repository apache/rocketmq-client-cpp, pull requests merged in 2019-07, with the labels that each got.

#157 remove removeDropedPullRequestOpaque and deleteOpaqueForDropPullRequest.
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/common/AsyncArg.h
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/consumer/PullRequest.cpp
  src/consumer/PullRequest.h
  src/consumer/Rebalance.cpp
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
Labels: remove useless code

#139 Export send batch messages api in c style.
  example/CBatchProducer.c
  include/CBatchMessage.h
  include/CProducer.h
  src/extern/CBatchMessage.cpp
  src/extern/CProducer.cpp
Labels: new feature

#156 [ISSUE #137] split TcpRemotingClient::m_ioService into m_dispatchService and m_handleService
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
Labels: enhancement

#158 merge m_futureTable and m_asyncFutureTable together.
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
Labels: enhancement

#154 [Feature] Support producer transaction message
  example/TransactionProducer.cpp
  include/MQMessage.h
  include/SendResult.h
  include/TransactionListener.h
  include/TransactionMQProducer.h
  include/TransactionSendResult.h
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/message/MQMessageId.h
  src/producer/SendResult.cpp
  src/producer/TransactionMQProducer.cpp
  src/protocol/CommandHeader.cpp
  src/protocol/CommandHeader.h
  src/protocol/RemotingCommand.cpp
  src/transport/ClientRemotingProcessor.cpp
  src/transport/ClientRemotingProcessor.h
Labels: new feature

#138 Add GetLatestErrorMessage feature
  include/CErrorMessage.h
  src/common/MQClientErrorContainer.cpp
  src/common/MQClientErrorContainer.h
  src/extern/CErrorMessage.cpp
  src/extern/CProducer.cpp
  src/extern/CPullConsumer.cpp
  src/extern/CPushConsumer.cpp
Labels: new feature
