Repository apache/rocketmq-client-cpp, pull requests merged in 2019-08, with the labels that each got.

#127 Support muti-thread compile in build.sh
  build.sh
Labels: enhancement

#172 Format the codes and remove warnings
  example/CBatchProducer.c
  include/CErrorMessage.h
  src/common/MQClientErrorContainer.cpp
  src/common/MQClientErrorContainer.h
  src/extern/CErrorMessage.cpp
  src/extern/CProducer.cpp
  src/extern/CPullConsumer.cpp
  src/extern/CPushConsumer.cpp
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpTransport.cpp
Labels: remove useless code

#167 boost build64 on windows
  README.md
  win32_build.bat
Labels: enhancement

#175 [ISSUE#145] Wrong lock flag for pull request in orderly consume when unlock bug
  src/consumer/Rebalance.cpp
Labels: bug

#176 Add license and notice binary to prepare release
  distribution/LICENSE-BIN
  distribution/NOTICE-BIN
  src/thread/disruptor/batch_descriptor.h
  src/thread/disruptor/claim_strategy.h
  src/thread/disruptor/event_processor.h
  src/thread/disruptor/event_publisher.h
  src/thread/disruptor/exception_handler.h
  src/thread/disruptor/exceptions.h
  src/thread/disruptor/interface.h
  src/thread/disruptor/ring_buffer.h
  src/thread/disruptor/sequence.h
  src/thread/disruptor/sequence_barrier.h
  src/thread/disruptor/sequencer.h
  src/thread/disruptor/utils.h
  src/thread/disruptor/wait_strategy.h
Labels: enhancement

#181 fixed dangling point in GetLatestErrorMessage.
  src/common/MQClientErrorContainer.cpp
  src/common/MQClientErrorContainer.h
  src/extern/CErrorMessage.cpp
  src/extern/CProducer.cpp
  src/extern/CPullConsumer.cpp
  src/extern/CPushConsumer.cpp
Labels: bug
