Repository apache/rocketmq-client-cpp, pull requests merged in 2020-01, with the labels that each got.

#209 fix(consumer): fix the issue that msg lost when send back to broker failed.
  include/DefaultMQPullConsumer.h
  include/DefaultMQPushConsumer.h
  include/MQConsumer.h
  src/consumer/ConsumeMessageConcurrentlyService.cpp
  src/consumer/ConsumeMessageOrderlyService.cpp
  src/consumer/ConsumeMsgService.h
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
Labels: bug

#210 fix(consumer): send back error when consuming failed.
  include/DefaultMQPullConsumer.h
  include/DefaultMQPushConsumer.h
  include/MQConsumer.h
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/common/MQClient.cpp
  src/consumer/ConsumeMessageConcurrentlyService.cpp
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/consumer/Rebalance.cpp
Labels: bug

#213 fix(producer) crash in DestroyProducer shutdown.
  src/extern/CProducer.cpp
Labels: bug

#214 fix(unittest): refactor some unitests
  .travis.yml
  CMakeLists.txt
  build.sh
  src/extern/CPullConsumer.cpp
  src/protocol/CommandHeader.cpp
  test/CMakeLists.txt
  test/src/extern/CMessageTest.cpp
  test/src/extern/CProducerTest.cpp
  test/src/extern/CPullConsumerTest.cpp
Labels: unit test

#215 feat(codecov): open code coverage for unit test
  .travis.yml
  CMakeLists.txt
  build.sh
  test/CMakeLists.txt
Labels: unit test

#216 feat(codecov): add logo for code coverage
  .travis.yml
  README.md
Labels: unit test

#217 fix(format): format code style for cmakelist
  .travis.yml
  CMakeLists.txt
  build.sh
  libs/signature/CMakeLists.txt
  project/CMakeLists.txt
  test/CMakeLists.txt
Labels: unit test

#218 fix(unittest): open some test cases
  src/message/MQDecoder.cpp
  test/src/MQClientManagerTest.cpp
  test/src/common/UrlTest.cpp
  test/src/message/BatchMessageTest.cpp
  test/src/message/MQDecoderTest.cpp
  test/src/message/MQMessageTest.cpp
  test/src/message/StringIdMakerTest.cpp
  test/src/transport/ClientRemotingProcessorTest.cpp
Labels: unit test

#220 fix(doc): update notice and open statistic label
  NOTICE
  README.md
Labels: enhancement

#222 feat(client): add timer to clean off line broker and test case.
  .gitignore
  build.sh
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/MQClientManager.cpp
  src/MQClientManager.h
  src/common/TopAddressing.h
  src/transport/TcpRemotingClient.h
  test/src/MQClientAPIImpTest.cpp
  test/src/MQClientFactoryTest.cpp
Labels: enhancement

#223 fix(protocol): delete string print in header decode and open test cases.
  src/protocol/CommandHeader.cpp
  test/src/message/MQMessageExtTest.cpp
  test/src/producer/StringIdMakerTest.cpp
  test/src/protocol/CommandHeaderTest.cpp
  test/src/protocol/ConsumerRunningInfoTest.cpp
  test/src/protocol/LockBatchBodyTest.cpp
Labels: bug

#225 fix(send): try to use command v2 to send messages
  src/MQClientAPIImpl.cpp
  src/MQClientFactory.cpp
  src/common/AsyncCallbackWrap.cpp
  src/common/AsyncCallbackWrap.h
  src/common/MQVersion.cpp
  src/common/MQVersion.h
  src/common/VirtualEnvUtil.cpp
  src/producer/DefaultMQProducer.cpp
  src/protocol/CommandHeader.cpp
  src/protocol/CommandHeader.h
  src/protocol/RemotingCommand.cpp
  test/src/common/MQVersionTest.cpp
  test/src/common/VirtualEnvUtilTest.cpp
  test/src/protocol/CommandHeaderTest.cpp
Labels: bug, enhancement

#227 feat(memleak): remove mem leak in factory schedule task.
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/common/MQClient.cpp
Labels: enhancement

#228 feat(libevent): update libevent to v2.1.11 to avoid get mutex time out.
  build.sh
Labels: bug, external

#230 feat(version): add maxConsumerTimes to support higher client version
  include/DefaultMQPushConsumer.h
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/consumer/ConsumeMessageConcurrentlyService.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/protocol/CommandHeader.cpp
  src/protocol/CommandHeader.h
  test/src/MQClientAPIImpTest.cpp
  test/src/protocol/CommandHeaderTest.cpp
Labels: enhancement

#232 feat(callback): use start pointer to manager callbacks
  src/MQClientAPIImpl.cpp
  src/common/AsyncCallbackWrap.cpp
  src/common/AsyncCallbackWrap.h
  src/transport/ResponseFuture.cpp
  src/transport/ResponseFuture.h
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
  test/src/MQClientAPIImpTest.cpp
  test/src/transport/ResponseFutureTest.cpp
Labels: enhancement

#233 feat(consumer): remove event if consumer service shutdown
  src/consumer/ConsumeMessageConcurrentlyService.cpp
  src/consumer/DefaultMQPushConsumer.cpp
Labels: enhancement

#234 fix(build): close code coverage link as default
  CMakeLists.txt
Labels: enhancement
