Repository apache/rocketmq-client-cpp, pull requests merged in 2020-02, with the labels that each got.

#236 feat(apis):refactor apis for CPP styles
  include/Arg_helper.h
  include/AsyncCallback.h
  include/DefaultMQProducer.h
  include/DefaultMQPullConsumer.h
  include/DefaultMQPushConsumer.h
  include/MQClient.h
  include/MQClientException.h
  include/MQMessage.h
  include/MQMessageExt.h
  include/MQMessageListener.h
  include/MQMessageQueue.h
  include/MQSelector.h
  include/MQueueListener.h
  include/PullResult.h
  include/SendResult.h
  include/TransactionMQProducer.h
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  test/src/message/MQMessageIdTest.cpp
  test/src/message/MQMessageTest.cpp
Labels: enhancement

#237 fix(build): fix variable in build script
  build.sh
Labels: bug

#238 feat(package): add rpm build and dpkg build script
  dep/build.sh
  dep/rocketmq_amd64/DEBIAN/control
  dep/rocketmq_amd64/DEBIAN/postinst
  rpm/build.sh
  rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
Labels: enhancement

#239 fix(package):update package script
  dep/build.sh
  rpm/build.sh
Labels: enhancement

#240 feat(release): update version to prepare to release v2
  README.md
  dep/rocketmq_amd64/DEBIAN/control
  distribution/deploy.sh
  rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
  src/common/DefaultMQClient.cpp
Labels: enhancement

#241 heap-buffer-overflow risk
  src/protocol/CommandHeader.cpp
Labels: enhancement

#244 chore(license): add missed license header in some files
  dep/build.sh
  rpm/build.sh
  src/producer/DefaultMQProducer.cpp
  src/producer/TransactionMQProducer.cpp
Labels: enhancement

#249 style(license): add license header for script files
  dep/rocketmq_amd64/DEBIAN/control
  dep/rocketmq_amd64/DEBIAN/postinst
  rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
Labels: enhancement

#248 fix(build): fix variable check error in the build script
  build.sh
Labels: enhancement

#250 fix(package): remove unnecessary lines and use sh to run postinst
  dep/rocketmq_amd64/DEBIAN/control
  dep/rocketmq_amd64/DEBIAN/postinst
Labels: bug

#246 fix(transaction): failed to select transaction producer to call local state checker
  src/MQClientFactory.cpp
  src/extern/CProducer.cpp
Labels: bug

#242 test(unittest): add some test cases for default producer implement.
  src/MQClientAPIImpl.cpp
  src/MQClientAPIImpl.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/common/DefaultMQClient.cpp
  src/common/NameSpaceUtil.cpp
  src/common/UtilAll.cpp
  src/common/UtilAll.h
  src/include/DefaultMQClient.h
  src/producer/TopicPublishInfo.h
  test/src/common/NameSpaceUtilTest.cpp
  test/src/common/UtilAllTest.cpp
  test/src/producer/DefaultMQProducerImplTest.cpp
  test/src/producer/TopicPublishInfoTest.cpp
Labels: unit test

#251 refactor(warning): remove warnings in header files
  include/DefaultMQProducer.h
  include/DefaultMQPushConsumer.h
  include/TransactionMQProducer.h
  src/common/DefaultMQClient.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/include/DefaultMQClient.h
  src/producer/DefaultMQProducer.cpp
  src/producer/TransactionMQProducer.cpp
Labels: refactor

#254 feat(build): add the script to package static lib on macOS.
  build.sh
Labels: enhancement

#252 refactor(transaction): use userdata to cache the local checker callback
  src/extern/CProducer.cpp
Labels: refactor

#256 feat(jsoncpp): update jsoncpp to 0.10.7 in order to fix build error by gcc7+
  README.md
  build.sh
  example/common.h
Labels: bug, enhancement

#257 feat(memory): add asan/lsan support, and formatting code.
  CMakeLists.txt
  build.sh
  distribution/deploy.sh
  format.sh
Labels: enhancement

#258 feat(producer): add regionId support in the send result
  build.sh
  include/SendResult.h
  src/MQClientAPIImpl.cpp
  src/producer/SendResult.cpp
  src/protocol/CommandHeader.cpp
  src/protocol/CommandHeader.h
  test/src/producer/DefaultMQProducerImplTest.cpp
  test/src/protocol/CommandHeaderTest.cpp
Labels: enhancement

#259 fix(test): fix the heap-buffer-overflow bug and bad/invalid test cases.
  test/src/common/MemoryBlockTest.cpp
Labels: unit test

#260 feat(orderly): add sharding key in the message property
  src/extern/CProducer.cpp
Labels: enhancement

#261 feat(version): add api to get SDK versions
  include/CCommon.h
  include/CProducer.h
  include/CPullConsumer.h
  include/CPushConsumer.h
  include/DefaultMQProducer.h
  include/DefaultMQPullConsumer.h
  include/DefaultMQPushConsumer.h
  include/TransactionMQProducer.h
  src/MQClientFactory.cpp
  src/MQClientFactory.h
  src/common/DefaultMQClient.cpp
  src/consumer/DefaultMQPullConsumer.cpp
  src/consumer/DefaultMQPullConsumerImpl.cpp
  src/consumer/DefaultMQPushConsumer.cpp
  src/consumer/DefaultMQPushConsumerImpl.cpp
  src/consumer/DefaultMQPushConsumerImpl.h
  src/extern/CProducer.cpp
  src/extern/CPullConsumer.cpp
  src/extern/CPushConsumer.cpp
  src/include/DefaultMQClient.h
  src/producer/DefaultMQProducer.cpp
  src/producer/DefaultMQProducerImpl.cpp
  src/producer/DefaultMQProducerImpl.h
  src/producer/TransactionMQProducer.cpp
  src/protocol/ConsumerRunningInfo.cpp
  src/protocol/ConsumerRunningInfo.h
  src/transport/TcpRemotingClient.cpp
  src/transport/TcpRemotingClient.h
  test/src/MQClientAPIImpTest.cpp
  test/src/MQClientFactoryTest.cpp
  test/src/extern/CProducerTest.cpp
  test/src/extern/CPullConsumerTest.cpp
  test/src/extern/CPushConsumerTest.cpp
  test/src/protocol/ConsumerRunningInfoTest.cpp
Labels: enhancement

#263 fix(memory): heap-buffer-overflow due to wrong use of strcpy.
  test/src/common/big_endianTest.cpp
Labels: bug

#264 fix(memery): heap-buffer-overflow risk due to wrong use of string constructor.
  src/protocol/LockBatchBody.cpp
Labels: bug

#265 refactor(build): use dynamic cpu cores to compile code.
  build.sh
Labels: enhancement, refactor

#266 chore(release): update version to release 2.0.1
  dep/rocketmq_amd64/DEBIAN/control
  distribution/deploy.sh
  rpm/rocketmq_x64/CENTOS/rocketmq-client-cpp.spec
  src/common/DefaultMQClient.cpp
Labels: enhancement
