Repository apache/rocketmq-client-cpp, pull requests merged in 2022-08, with the labels that each got.

#437 [ISSUE 436] Downloading dependent packages without checking certificate in compile shell.
  build.sh
Labels: enhancement, unit test

#434 [ISSUE-435][PART-A]Support receiving traceOn signal.
  include/SendResult.h
  src/MQClientAPIImpl.cpp
  src/producer/SendResult.cpp
  src/protocol/RemotingCommand.cpp
  src/protocol/RemotingCommand.h
Labels: enhancement, SoC

#417 adapt to new version of boost and fix compile error
  src/common/ByteOrder.h
  src/log/Logging.h
  src/producer/TransactionMQProducerImpl.h
Labels: enhancement, disscuss
